NOTHING_CODE = 0
MOVE_CODE = 1
TURN_CODE = 2

MOVE_FORWARD = [MOVE_CODE, 100]
MOVE_BACKWARD = [MOVE_CODE, -100]
STOP = [NOTHING_CODE, 0]
TURN_LEFT = [TURN_CODE, -100]
TURN_RIGHT = [TURN_CODE, 100]

# for death rod
UP = 0
DOWN = 1